version: '3'

x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file

services:
  database:
    image: postgres:15-alpine
    container_name: ordabok_db
    env_file: .env
    restart: unless-stopped
    volumes:
      - ordabok_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  ordabok_db_data:
